#-------------------------------
# General Site Settings

title: Mick MacCallum | Portfolio

# Here you can add link in main menu
menu:
- {name: Work, url: 'work', icon: 'ion ion-ios-briefcase'}
- {name: Blog, url: 'blog', icon: 'ion ion-ios-paper'}
- {name: Contact, url: 'contact', icon: 'ion ion-ios-mail'}

#-------------------------------
# About Section

avatar: 05.jpg
name: Mick MacCallum
my-job: Senior Software Engineer
description: I'm a software engineer focused on mobile development. I'm primarily experienced with native iOS development although lately I've been using React Native more often than not.
# description: I’m a product designer, illustrator & side-project enthusiast. I’m currently build great products at Pixel Media.
email: micksmaccallum@gmail.com

#-------------------------------
# Skills Section

skills-title: Professional Skills
skills:
- {name: Communication, value: '90'}
- {name: Learning, value: '95'} 
- {name: Planning, value: '60'}
- {name: Visual Design, value: '80'}
- {name: UX Design, value: '85'}
- {name: Programming, value: '70'}

#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {company-name: Evil Studios Limited, duration: 2018 - Present, job-position: Senior Software Engineer, description: "Lead developer for Evil Apples' iOS and Android apps. Oversaw integration of React Native on both platforms and assisted in the development of new backend features for its Node RESTful webservice."}

- {company-name: Evil Studios Limited, duration: 2016 - 2018, job-position: Software Engineer, description: "Developer working on the Evil Apples iOS app, a top 25 card game in the App Store. Responsible for daily maintenance, bug fixes and new feature development from planning and specification to deployment."}

- {company-name: Stack Overflow, duration: 2014 - 2016, job-position: Elected Community Moderator, description: "Assisted a team of moderators in community management and moderation including detecting and preventing spam creation as well as guiding new users to use Stack Overflow more effectively."}

#-------------------------------
# Education Section

education-title: Education
education:
- {degree: Bachelor of Software Engineering (B.SE.), years: 2015 - 2017, organization: "Florida Gulf Coast University, Fort Myers, FL", description: null}

- {degree: Associate of Arts (AA), years: 2012 - 2015, organization: "Florida SouthWestern State College, Fort Myers, FL", description: null}

#-------------------------------
# Clients Section
# clients-title: Clienst
# clients:
# - {
#   name: "Dianna Smiley",
#   title: "Social Media, Co and Co",
#   quote: "<p><strong>Working with Chris was the highlight of my career.</strong> Art party before they sold out lo-fi cronut. Narwhal normcore kinfolk crucifix cronut coloring book man braid lomo fixie sartorial helvetica cornhole activated charcoal ethical.</p>"
# }
# - {
#   name: "Loki Bright",
#   title: "Director of Design, New Devi Art",
#   quote: "<p><strong>While we all felt that Chris was a great.</strong> Woke lumbersexual iceland truffaut blog, deep v poke ramps vexillologist heirloom flexitarian taxidermy lomo seitan gastropub. Bespoke vape next level meditation tattooed cred.</p>"
# }
# - {
#   name: "Korbyn Colon",
#   title: "Art Director, LTD Corporate",
#   quote: "<p><strong>Chillwave ethical enamel pin, fashion axe leggings.</strong> Bespoke franzen umami sustainable. Chambray keffiyeh cred sriracha. Hashtag street art humblebrag pok pok viral meggings tacos chambray narwhal gentrify woke etsy.</p>"
# }
# - {
#   name: "Gracelyn Mason",
#   title: "Journalist, The Best Newspaper",
#   quote: "<p><strong>Skateboard iceland distillery succulents dreamcatcher cloud bread ugh keffiyeh unicorn austin.</strong> Palo santo health goth forage four dollar toast. Thundercats ramps irony meggings lo-fi kogi. Activated charcoal pitchfork you probably haven't heard of them squid.</p>"
# }

#-------------------------------
# Work Section

projects:
- {
  name: Design Talks, 
  image: '10.jpg'
}
- {
  name: Abstract Page, 
  image: '11.jpg'
}
- {
  name: Round Shapes, 
  image: '12.jpg'
}
- {
  name: Color Palette,
  image: '13.jpg'
}
- {
  name: Color Palette,
  image: '14.jpg'
}
- {
  name: Color Palette,
  image: '15.jpg'
}

#-------------------------------
# Social Settings

social:
- {link: "https://www.stackoverflow.com/users/716216", icon: ion-ios-code, title: StackOverflow }
- {link: "https://www.github.com/0x7fs", icon: ion-logo-github, title: GitHub }
- {link: "https://humblebots.io/", icon: ion-logo-apple, title: Apple App Store Listings }
# - {link: "https://apps.apple.com/us/developer/michael-maccallum/id284776469", icon: ion-md-document, title: Download Résumé }

# social network icons available (https://ionicons.com/): 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' /

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------